parent_config: .swiftlint.yml

line_length:
  warning: 150
  error: 250

function_body_length:
  warning: 80
  error: 150

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 400
  error: 700

file_length:
  warning: 800
  error: 1300

cyclomatic_complexity:
  warning: 12
  error: 25

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length:
    warning: 2
    error: 2
  allowed_symbols:
    - "_"
