@testable import Emuqu
import XCTest

/// The app's HRV metrics, checked against ECG-derived beat annotations.
///
/// ## The gap this closes
///
/// The app reports RMSSD, SDNN and pNN50 and nothing demonstrated those numbers
/// are right. The existing unit tests exercise the functions against hand-made
/// input — useful for edge cases, silent about accuracy, because the author of
/// the test and the author of the code shared the same idea of the answer.
///
/// ## What this validates, and what it cannot
///
/// Two questions hide inside "is the HRV accurate":
///
///   1. Does the app compute the standard metrics correctly from a beat series?
///   2. Does a Polar H10 find beats as well as a clinical ECG?
///
/// (2) is the sensor's claim, established in published validation literature,
/// and no test here can reach it — the app never sees an ECG to compare
/// against. Pretending otherwise would be the kind of unearned assurance the
/// copy linter exists to stop.
///
/// (1) is entirely the app's responsibility and is what these tests cover:
/// 6,000 real RR intervals from 20 subjects, taken from beat annotations made
/// on 24-hour clinical Holter recordings, run through the app's own
/// `computeTimeDomain` and compared against an independent implementation of
/// the Task Force (1996) definitions written in Python.
///
/// Independent matters. Two callers of the same library agree while both being
/// wrong; a second implementation written from the published definitions
/// disagrees when either side is.
///
/// ## Source and licence
///
/// MIT Normal Sinus Rhythm RR Interval Database (nsr2db) v1.0.0 on PhysioNet,
/// Open Data Commons Attribution License v1.0. Fixtures are generated by
/// `scripts/fetch_hrv_reference.py`; provenance is in
/// `docs/hrv-reference-data.md`.
final class HRVReferenceValidationTests: XCTestCase {
    private struct Expected: Decodable {
        let meanRR: Double
        let sdnn: Double
        let rmssdUnfiltered: Double
        let pnn50Unfiltered: Double
        let hrFromMeanRR: Double
    }

    private struct Record: Decodable {
        let record: String
        let age: String?
        let sex: String?
        let sourceSHA256: String
        let rrMs: [Int]
        let expected: Expected
    }

    private struct Fixtures: Decodable {
        let records: [Record]
    }

    private static let fixtures: Fixtures = {
        let data = Data(HRVReferenceFixtures.json.replacingOccurrences(of: "\n", with: "").utf8)
        // swiftlint:disable:next force_try
        return try! JSONDecoder().decode(Fixtures.self, from: data)
    }()

    /// Tolerance is tight on purpose.
    ///
    /// Both sides consume the same integer millisecond series and both compute
    /// in double precision, so the only legitimate difference is floating-point
    /// association order. Anything larger is an arithmetic disagreement, which
    /// is the thing being looked for.
    private let tolerance = 1e-6

    private func analyse(_ record: Record) -> TimeDomainMetrics? {
        var elapsed: Int64 = 0
        let points: [RRPoint] = record.rrMs.map { rr in
            let point = RRPoint(t_ms: elapsed, rr_ms: rr)
            elapsed += Int64(rr)
            return point
        }
        let series = RRSeries(points: points, sessionId: UUID(), startDate: Date())
        let clean = [ArtifactFlags](repeating: .clean, count: points.count)
        return TimeDomainAnalyzer.computeTimeDomain(
            series, flags: clean, windowStart: 0, windowEnd: points.count
        )
    }

    // MARK: - The fixtures themselves

    /// A validation suite that silently loaded nothing would pass every test
    /// below. This is the same failure this repository keeps finding, so the
    /// corpus is asserted before it is used.
    func testFixtureCorpusIsPresentAndPlausible() {
        let records = Self.fixtures.records
        XCTAssertEqual(records.count, 20, "Expected 20 reference recordings")
        XCTAssertEqual(records.reduce(0) { $0 + $1.rrMs.count }, 6000,
                       "Expected 6,000 reference RR intervals")
        for record in records {
            XCTAssertEqual(record.sourceSHA256.count, 64,
                           "\(record.record) is missing its source checksum")
            XCTAssertTrue(record.rrMs.allSatisfy { (300 ... 2000).contains($0) },
                          "\(record.record) contains a non-physiological interval")
        }
    }

    // MARK: - The app against the reference

    /// `computeTimeDomain` derives mean RR and SDNN from the artefact-filtered
    /// series, which here is every interval, so both are directly comparable.
    func testMeanRRAndSDNNMatchTheReferenceOnEveryRecord() throws {
        for record in Self.fixtures.records {
            let metrics = try XCTUnwrap(analyse(record), "\(record.record) produced no metrics")
            XCTAssertEqual(metrics.meanRR, record.expected.meanRR, accuracy: tolerance,
                           "Mean RR disagrees on \(record.record)")
            XCTAssertEqual(metrics.sdnn, record.expected.sdnn, accuracy: tolerance,
                           "SDNN disagrees on \(record.record)")
        }
    }

    /// RMSSD from the pure formula — `rmssd(fromCleanRRs:)`, no ectopic filter
    /// — against the reference, which is also unfiltered. This is the
    /// arithmetic check: two implementations of one published definition, on
    /// 6,000 real intervals.
    func testUnfilteredRMSSDMatchesTheReferenceOnEveryRecord() throws {
        for record in Self.fixtures.records {
            let rr = record.rrMs.map(Double.init)
            let value = try XCTUnwrap(TimeDomainAnalyzer.rmssd(fromCleanRRs: rr),
                                      "\(record.record) produced no RMSSD")
            XCTAssertEqual(value, record.expected.rmssdUnfiltered, accuracy: tolerance,
                           "Unfiltered RMSSD disagrees on \(record.record)")
        }
    }

    // MARK: - The ectopic filter, which is why the two RMSSDs differ

    /// `computeTimeDomain` filters ectopic beats before taking successive
    /// differences; `rmssd(fromCleanRRs:)` does not. So the pipeline's RMSSD
    /// must be no larger than the raw one — removing outliers can only shrink
    /// a root-mean-square of differences.
    ///
    /// This is the relationship the first version of these tests got wrong. It
    /// compared the pipeline against an unfiltered reference and read a
    /// deliberate, documented design choice as a defect: on nsr005 the app
    /// reported 16.03 against 28.98, which is the filter working, not failing.
    func testPipelineRMSSDIsNeverLargerThanTheUnfilteredValue() throws {
        var narrowed = 0
        for record in Self.fixtures.records {
            let metrics = try XCTUnwrap(analyse(record))
            let raw = try XCTUnwrap(TimeDomainAnalyzer.rmssd(fromCleanRRs: record.rrMs.map(Double.init)))
            XCTAssertLessThanOrEqual(metrics.rmssd, raw + tolerance,
                                     "Ectopic filtering raised RMSSD on \(record.record)")
            if metrics.rmssd < raw - tolerance { narrowed += 1 }
        }
        XCTAssertGreaterThan(narrowed, 0,
                             "No record was affected by ectopic filtering — the corpus cannot "
                                 + "distinguish a working filter from one that does nothing")
    }

    /// pNN50 against the reference on every record the ectopic filter leaves
    /// whole: there the pipeline's successive differences are the raw ones, so
    /// its pNN50 must equal the unfiltered reference (given to 6 decimals).
    func testPNN50MatchesTheReferenceWhereNoBeatIsFiltered() throws {
        var compared = 0
        for record in Self.fixtures.records {
            let rr = record.rrMs.map(Double.init)
            guard TimeDomainAnalyzer.filterEctopicBeats(rr).count == rr.count else { continue }
            let metrics = try XCTUnwrap(analyse(record))
            XCTAssertEqual(metrics.pnn50, record.expected.pnn50Unfiltered, accuracy: 1e-5,
                           "pNN50 disagrees on \(record.record)")
            compared += 1
        }
        XCTAssertGreaterThan(compared, 0, "No record reached the pNN50 comparison")
    }

    /// The filter must remove beats, not invent them.
    func testEctopicFilterOnlyEverRemovesBeats() {
        for record in Self.fixtures.records {
            let rr = record.rrMs.map(Double.init)
            let filtered = TimeDomainAnalyzer.filterEctopicBeats(rr)
            XCTAssertLessThanOrEqual(filtered.count, rr.count, "Filter grew \(record.record)")
            XCTAssertTrue(filtered.allSatisfy { rr.contains($0) },
                          "Filter produced a value not present in \(record.record)")
        }
    }

    // MARK: - Properties that must hold on real data

    /// Mean HR is NOT the reciprocal of mean RR in this app: it comes from
    /// rolling 10-second windows, and the mean of reciprocals is not the
    /// reciprocal of the mean. Asserting equality was this suite's own bug —
    /// it failed on nsr001 with 88.53 against 88.46, which is Jensen's
    /// inequality, not an error. What must hold is that they agree in scale.
    func testMeanHeartRateAgreesInScaleWithMeanRR() throws {
        for record in Self.fixtures.records {
            let metrics = try XCTUnwrap(analyse(record))
            let naive = record.expected.hrFromMeanRR
            XCTAssertEqual(metrics.meanHR, naive, accuracy: max(2.0, naive * 0.05),
                           "Mean HR is out of scale with mean RR on \(record.record)")
            XCTAssertTrue((30 ... 200).contains(metrics.meanHR),
                          "\(record.record) implies \(metrics.meanHR) bpm")
        }
    }

    /// Every metric is a length in milliseconds or a percentage; none can be
    /// negative, and a NaN from a divide-by-zero would propagate silently into
    /// a recovery score.
    func testEveryMetricIsFiniteAndNonNegative() throws {
        for record in Self.fixtures.records {
            let metrics = try XCTUnwrap(analyse(record))
            for (name, value) in [("meanRR", metrics.meanRR), ("sdnn", metrics.sdnn),
                                  ("rmssd", metrics.rmssd), ("pnn50", metrics.pnn50),
                                  ("sdsd", metrics.sdsd), ("meanHR", metrics.meanHR)] {
                XCTAssertTrue(value.isFinite, "\(name) is not finite on \(record.record)")
                XCTAssertGreaterThanOrEqual(value, 0, "\(name) is negative on \(record.record)")
            }
        }
    }

    /// Shifting every interval by a constant moves the mean and leaves the
    /// variability measures alone. True of the definitions, and a check the
    /// reference values cannot provide because it is a relationship between two
    /// runs rather than a value.
    func testVariabilityIsInvariantUnderAConstantShift() throws {
        for record in Self.fixtures.records.prefix(5) {
            let base = try XCTUnwrap(analyse(record))
            let shifted = Record(record: record.record, age: record.age, sex: record.sex,
                                 sourceSHA256: record.sourceSHA256,
                                 rrMs: record.rrMs.map { $0 + 100 }, expected: record.expected)
            let moved = try XCTUnwrap(analyse(shifted))
            XCTAssertEqual(moved.meanRR, base.meanRR + 100, accuracy: 1e-9)
            XCTAssertEqual(moved.sdnn, base.sdnn, accuracy: 1e-9)
        }
    }
}
