import CoreLocation
import SwiftUI

/// Hero card for a completed workout — the single focal point at the top of
/// the post-workout summary. Mirrors the Morning Results recovery-score
/// hero pattern: a prominent central metric, a short narrative below, and
/// a consistent card container.
///
/// Design rationale (parity with Morning Results):
///   - One central focal metric instead of a 15-row table.
///   - All-caps section header in tracked caption weight (same typography
///     as TrainingReadinessCard / RecoveryScoreCard).
///   - Single narrative sentence telling the story of the workout.
///   - Consistent padding + `cornerRadius(16)` + `AppTheme.cardBackground`.
///
/// Inputs are plain values, not an HRVSession — keeps this card pure and
/// testable, and lets the caller do any data-shaping in one place.
struct WorkoutHeroCard: View {
    /// Sport for the icon + label ("WALK", "RUN", etc.).
    let sport: Sport
    /// Formatted main distance string in the user's units (e.g. "3.95 mi").
    let distanceLabel: String
    /// Formatted duration string (e.g. "1:03:07").
    let durationLabel: String
    /// Formatted average pace string (e.g. "15:59 /mi") — optional.
    let paceLabel: String?
    /// When the session ended (for the "2 hours ago" relative date).
    let endDate: Date?
    /// α1 band the user spent the most time in. Drives the colored pill.
    let dominantAlpha1Band: LiveDFAAnalyzer.Band?
    /// Plain-English one-sentence narrative of the workout. Generated by
    /// the caller from actual session metrics — never invented.
    let narrative: String
    /// Optional compact polyline to trace as a visual hook.
    let routeCoordinates: [CLLocationCoordinate2D]

    var body: some View {
        VStack(spacing: 14) {
            sportHeaderBand
            distanceDurationStack
            alpha1BandPill
            routeTrace
            narrativeText
        }
        .padding()
        .frame(maxWidth: .infinity)
        .background(AppTheme.cardBackground)
        .cornerRadius(16)
    }

    /// --- Top band: sport header with icon + all-caps label ---
    private var sportHeaderBand: some View {
        HStack(spacing: 10) {
            Image(systemName: sport.icon)
                .font(.title3.weight(.semibold))
                .foregroundStyle(AppTheme.terracotta)
                .frame(width: 36, height: 36)
                .background(AppTheme.terracotta.opacity(0.15))
                .clipShape(Circle())
            Text(sport.localizedName.uppercased())
                .font(.caption.weight(.bold))
                .tracking(1.5)
                .foregroundStyle(AppTheme.textTertiary)
            Spacer()
            if let endDate {
                Text(relativeDate(endDate))
                    .font(.caption)
                    .foregroundStyle(AppTheme.textTertiary)
            }
        }
    }

    /// --- Centerpiece: big distance + duration stack ---
    /// --- Narrative (plain-English story of the workout) ---
    @ViewBuilder
    private var narrativeText: some View {
        if !narrative.isEmpty {
            Text(narrative)
                .font(.callout)
                .foregroundStyle(AppTheme.textSecondary)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private var distanceDurationStack: some View {
        VStack(spacing: 4) {
            Text(distanceLabel)
                .scaledFont(size: 54, weight: .heavy)
                .foregroundStyle(AppTheme.textPrimary)
                .minimumScaleFactor(0.5)
                .lineLimit(1)
            durationAndPaceRow
        }
        .padding(.vertical, 4)
    }

    private var durationAndPaceRow: some View {
        HStack(spacing: 10) {
            Text(durationLabel)
                .font(.title3.monospacedDigit().weight(.semibold))
                .foregroundStyle(AppTheme.textSecondary)
            paceLabelText
        }
    }

    @ViewBuilder
    private var paceLabelText: some View {
        if let paceLabel {
            Text(String(localized: "·", bundle: LanguageManager.appBundle))
                .font(.title3)
                .foregroundStyle(AppTheme.textTertiary)
            Text(paceLabel)
                .font(.title3.monospacedDigit().weight(.semibold))
                .foregroundStyle(AppTheme.textSecondary)
        }
    }

    /// --- α1 band pill (colored, communicates effort regime) ---
    @ViewBuilder
    private var alpha1BandPill: some View {
        if let band = dominantAlpha1Band, band != .unknown {
            bandPill(band: band)
        }
    }

    /// --- Route polyline trace (if GPS sport) ---
    @ViewBuilder
    private var routeTrace: some View {
        if routeCoordinates.count >= 2 {
            polylineTrace(coordinates: routeCoordinates)
                .frame(height: 56)
        }
    }

    private func bandPill(band: LiveDFAAnalyzer.Band) -> some View {
        let (color, label) = bandAppearance(band)
        return HStack(spacing: 6) {
            Circle().fill(color).frame(width: 8, height: 8)
            Text(label.uppercased())
                .font(.caption.weight(.bold))
                .tracking(1)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .foregroundStyle(bandTextColor(band))
        .background(color.opacity(0.14))
        .clipShape(Capsule())
    }

    /// The fill colours are too light for words on a light card (yellow on a
    /// 14% yellow wash fails contrast), so the label takes the darkened text
    /// variant of the same hue.
    private func bandTextColor(_ band: LiveDFAAnalyzer.Band) -> Color {
        switch band {
        case .belowAeT: AppTheme.sageText
        case .nearAeT: AppTheme.softGoldText
        case .aboveVT2: AppTheme.terracottaText
        case .unknown: AppTheme.textTertiary
        }
    }

    private func bandAppearance(_ band: LiveDFAAnalyzer.Band) -> (Color, String) {
        switch band {
        case .belowAeT: (AppTheme.sage, String(localized: "Easy · Below Aerobic Threshold", bundle: LanguageManager.appBundle))
        case .nearAeT: (.yellow, String(localized: "Threshold · Near LT1", bundle: LanguageManager.appBundle))
        case .aboveVT2: (Color(red: 0.90, green: 0.35, blue: 0.35), String(localized: "Very Hard · Above LT2", bundle: LanguageManager.appBundle))
        case .unknown: (AppTheme.textTertiary, String(localized: "α1 unavailable", bundle: LanguageManager.appBundle))
        }
    }

    /// Minimal polyline trace. Scales the coordinate range into the frame
    /// bounds and strokes the path — no map tiles, so renders in a single
    /// frame on any device.
    private func polylineTrace(coordinates: [CLLocationCoordinate2D]) -> some View {
        GeometryReader { geo in
            Path { Self.tracePath(&$0, coordinates: coordinates, in: geo.size) }
                .stroke(AppTheme.terracotta, style: StrokeStyle(lineWidth: 2.2, lineCap: .round, lineJoin: .round))
        }
    }

    /// One scale for both axes, so the trace keeps the route's shape: an
    /// east-west route stays a flat line instead of having its north-south
    /// wobble stretched to the full height. Longitude is shrunk by cos(lat)
    /// to put both axes in the same ground distance, and the trace is
    /// centred in the frame. A tiny epsilon floor on the span keeps a
    /// single-point route from dividing by zero.
    private static func tracePath(_ path: inout Path, coordinates: [CLLocationCoordinate2D], in size: CGSize) {
        guard let bounds = TraceBounds(coordinates) else { return }
        let span = max(0.0001, max(bounds.width, bounds.height))
        let scale = min(size.width, size.height) / CGFloat(span)
        let inset = CGPoint(
            x: (size.width - CGFloat(bounds.width) * scale) / 2,
            y: (size.height - CGFloat(bounds.height) * scale) / 2
        )
        for (i, c) in coordinates.enumerated() {
            let p = CGPoint(
                x: inset.x + CGFloat(bounds.x(c)) * scale,
                y: size.height - inset.y - CGFloat(bounds.y(c)) * scale
            )
            if i == 0 { path.move(to: p) } else { path.addLine(to: p) }
        }
    }

    /// A route's extent in degrees of latitude, with longitude converted to
    /// the same ground distance at the route's mid-latitude.
    private struct TraceBounds {
        let minLat: Double
        let minLon: Double
        let lonScale: Double
        let width: Double
        let height: Double

        init?(_ coordinates: [CLLocationCoordinate2D]) {
            let lats = coordinates.map(\.latitude)
            let lons = coordinates.map(\.longitude)
            guard let minLat = lats.min(), let maxLat = lats.max(),
                  let minLon = lons.min(), let maxLon = lons.max() else { return nil }
            self.minLat = minLat
            self.minLon = minLon
            lonScale = cos((minLat + maxLat) / 2 * .pi / 180)
            width = (maxLon - minLon) * lonScale
            height = maxLat - minLat
        }

        func x(_ c: CLLocationCoordinate2D) -> Double { (c.longitude - minLon) * lonScale }
        func y(_ c: CLLocationCoordinate2D) -> Double { c.latitude - minLat }
    }

    /// A workout that just ended reads "now", not "in 0 seconds": the end date
    /// can sit a moment after the clock read here, which the formatter
    /// rendered as a future time. Clamped to the present, and `.named` turns
    /// a zero offset into the locale's word for "now".
    private func relativeDate(_ date: Date) -> String {
        let formatter = RelativeDateTimeFormatter()
        formatter.locale = LanguageManager.appLocale
        formatter.dateTimeStyle = .named
        let now = Date()
        return formatter.localizedString(for: min(date, now), relativeTo: now)
    }
}
